Name: deployment
SchemaVersion: "1.0"
Triggers:
  - Type: PUSH
    Branches:
      - main
Compute:
  Type: EC2
  Fleet: Linux.x86-64.Large
  SharedInstance: true
Actions:
  build:
    Identifier: aws/build@v1
    Environment:
      Name: hub-account
      Connections:
        - Name: 435185141757
          Role: CodeCatalystWorkflowDevelopmentRole-tbelmega
    Inputs:
      Sources:
        - WorkflowSource
      Variables:
        - Name: LAUNCH_OPTIONS_SOLUTION_NAME
          Value: AccountAssessment
        - Name: LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET
          Value: solutions-poc
        - Name: LAUNCH_OPTIONS_VERSION
          Value: custom001
        - Name: LAUNCH_OPTIONS_REGION
          Value: us-west-2
    Outputs:
      AutoDiscoverReports:
        Enabled: false
        ReportNamePrefix: rpt
    Configuration:
      Steps:
        - Run: |
            set -e
            cd ./deployment
            chmod +x ./build-s3-dist.sh
            pwd
            ./build-s3-dist.sh $LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET $LAUNCH_OPTIONS_SOLUTION_NAME $LAUNCH_OPTIONS_VERSION
            cd ..
        - Run: |
            ASSET_BUCKET_NAME=$LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET-$LAUNCH_OPTIONS_REGION
            echo $ASSET_BUCKET_NAME
            set +e
            aws s3 mb s3://$ASSET_BUCKET_NAME/
            set -e
            BUCKET_NAME=$LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET-$LAUNCH_OPTIONS_REGION
            aws s3 ls s3://$BUCKET_NAME # test bucket exists - should not give an error
            cd ./deployment/global-s3-assets
            aws s3 cp . s3://$BUCKET_NAME/$LAUNCH_OPTIONS_SOLUTION_NAME/$LAUNCH_OPTIONS_VERSION/ --recursive --acl bucket-owner-full-control
            cd ../regional-s3-assets
            aws s3 cp . s3://$BUCKET_NAME/$LAUNCH_OPTIONS_SOLUTION_NAME/$LAUNCH_OPTIONS_VERSION/ --recursive --acl bucket-owner-full-control
            cd ..
      Container:
        Registry: CODECATALYST
        Image: CodeCatalystLinux_x86_64:2024_03
  deploy-hub:
    DependsOn:
      - build
    Identifier: aws/build@v1
    Environment:
      Name: hub-account
      Connections:
        - Name: 435185141757
          Role: CodeCatalystWorkflowDevelopmentRole-tbelmega
    Inputs:
      Variables:
        - Name: LAUNCH_OPTIONS_SOLUTION_NAME
          Value: AccountAssessment
        - Name: LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET
          Value: solutions-features-aaao-tbelmega
        - Name: LAUNCH_OPTIONS_VERSION
          Value: custom001
        - Name: LAUNCH_OPTIONS_REGION
          Value: us-west-2
        - Name: LAUNCH_OPTIONS_NAMESPACE
          Value: 'aaao-ccat'
        - Name: LAUNCH_OPTIONS_PREFIX
          Value: 'aaao-ccat'
        - Name: LAUNCH_OPTIONS_EMAIL
          Value: 'tbelmega@amazon.com'
        - Name: LAUNCH_OPTIONS_IP_RANGES
          Value: '0.0.0.0/1,128.0.0.0/1'
    Outputs:
      AutoDiscoverReports:
        Enabled: false
        ReportNamePrefix: rpt
    Configuration:
      Steps:
        - Run: |
            cd ./source
            echo $(ls)
            export SOLUTION_VERSION=$LAUNCH_OPTIONS_VERSION
            export SOLUTION_NAME=$LAUNCH_OPTIONS_SOLUTION_NAME
            export DIST_OUTPUT_BUCKET=$LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET
            npm run bootstrap
            npm run deploy:CI -- --parameters DeploymentNamespace=$LAUNCH_OPTIONS_NAMESPACE --parameters CognitoDomainPrefix=$LAUNCH_OPTIONS_PREFIX --parameters UserEmail=$LAUNCH_OPTIONS_EMAIL  --parameters AllowListedIPRanges=$LAUNCH_OPTIONS_IP_RANGES
      Container:
        Registry: CODECATALYST
        Image: CodeCatalystLinux_x86_64:2024_03
  deploy-orgmgmt:
    DependsOn:
      - deploy-hub
    Identifier: aws/build@v1
    Environment:
      Name: orgmgmt-account
      Connections:
        - Name: OrgMgmt
          Role: CodeCatalystWorkflowDevelopmentRole-tbelmega
    Inputs:
      Variables:
        - Name: LAUNCH_OPTIONS_SOLUTION_NAME
          Value: AccountAssessment
        - Name: LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET
          Value: solutions-features-aaao-tbelmega
        - Name: LAUNCH_OPTIONS_VERSION
          Value: custom001
        - Name: LAUNCH_OPTIONS_REGION
          Value: us-west-2
        - Name: LAUNCH_OPTIONS_NAMESPACE
          Value: 'aaao-ccat'
        - Name: LAUNCH_OPTIONS_HUB_ACC_ID
          Value: '435185141757'
    Outputs:
      AutoDiscoverReports:
        Enabled: false
        ReportNamePrefix: rpt
    Configuration:
      Steps:
        - Run: |
            cd ./source
            export SOLUTION_VERSION=$LAUNCH_OPTIONS_VERSION
            export SOLUTION_NAME=$LAUNCH_OPTIONS_SOLUTION_NAME
            export DIST_OUTPUT_BUCKET=$LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET
            npm run bootstrap
            npm run deployOrgMgmt -- --parameters DeploymentNamespace=$LAUNCH_OPTIONS_NAMESPACE --parameters HubAccountId=$LAUNCH_OPTIONS_HUB_ACC_ID
      Container:
        Registry: CODECATALYST
        Image: CodeCatalystLinux_x86_64:2024_03
