Name: deployment
SchemaVersion: "1.0"
Triggers:
  - Type: PUSH
    Branches:
      - main
Compute:
  Type: EC2
  Fleet: Linux.x86-64.Large
Actions:
  build:
    Identifier: aws/build@v1
    Inputs:
      Sources:
        - WorkflowSource
      Variables:
        - Name: LAUNCH_OPTIONS_SOLUTION_NAME
          Value: AccountAssessment
        - Name: LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET
          Value: solutions-features
        - Name: LAUNCH_OPTIONS_VERSION
          Value: custom001
        - Name: LAUNCH_OPTIONS_REGION
          Value: us-east-1
    Outputs:
      Artifacts:
        GlobalAssets:
          Files:
          - 'deployment/global-s3-assets/*'
        RegionalAssets:
          Files:
          - 'deployment/regional-s3-assets/*'
      AutoDiscoverReports:
        Enabled: false
        ReportNamePrefix: rpt
    Configuration:
      Steps:
        - Run: |
            set -e
            cd ./deployment
            chmod +x ./build-s3-dist.sh
            pwd
            ./build-s3-dist.sh $LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET $LAUNCH_OPTIONS_SOLUTION_NAME $LAUNCH_OPTIONS_VERSION
            cd ..
      Container:
        Registry: CODECATALYST
        Image: CodeCatalystLinux_x86_64:2024_03
  upload-to-s3:
    DependsOn:
      - build
    Identifier: aws/build@v1
    Environment:
      Name: hub-account
      Connections:
        - Name: 435185141757
          Role: CodeCatalystWorkflowDevelopmentRole-tbelmega
    Inputs:
      Artifacts:
        - GlobalAssets
        - RegionalAssets
      Sources:
        - WorkflowSource
      Variables:
        - Name: LAUNCH_OPTIONS_SOLUTION_NAME
          Value: AccountAssessment
        - Name: LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET
          Value: solutions-features-aaao-tbelmega
        - Name: LAUNCH_OPTIONS_VERSION
          Value: custom001
        - Name: LAUNCH_OPTIONS_REGION
          Value: us-east-1
    Outputs:
      AutoDiscoverReports:
        Enabled: false
        ReportNamePrefix: rpt
    Configuration:
      Steps:
        - Run: |
            echo $(aws sts get-caller-identity)
            ASSET_BUCKET_NAME=$LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET-$LAUNCH_OPTIONS_REGION
            echo $ASSET_BUCKET_NAME
            aws s3 mb s3://$ASSET_BUCKET_NAME/
            BUCKET_NAME=$LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET-$LAUNCH_OPTIONS_REGION
            aws s3 ls s3://$BUCKET_NAME # test bucket exists - should not give an error
            # Use the paths for GlobalAssets and RegionalAssets passed from previous action
            aws s3 cp $CATALYST_SOURCE_DIR_GlobalAssets/ s3://$BUCKET_NAME/$LAUNCH_OPTIONS_SOLUTION_NAME/$LAUNCH_OPTIONS_VERSION/ --recursive --acl bucket-owner-full-control
            aws s3 cp $CATALYST_SOURCE_DIR_RegionalAssets/ s3://$BUCKET_NAME/$LAUNCH_OPTIONS_SOLUTION_NAME/$LAUNCH_OPTIONS_VERSION/ --recursive --acl bucket-owner-full-control
            cd ..
      Container:
        Registry: CODECATALYST
        Image: CodeCatalystLinux_x86_64:2024_03
