Name: deployment
SchemaVersion: "1.0"
Triggers:
  - Type: PUSH
    Branches:
      - main
Compute:
  Type: EC2
  Fleet: Linux.x86-64.Large
Actions:
  build:
    Identifier: aws/build@v1
    Inputs:
      Sources:
        - WorkflowSource
      Variables:
        - Name: LAUNCH_OPTIONS_SOLUTION_NAME
          Value: AccountAssessment
        - Name: LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET
          Value: solutions-features
        - Name: LAUNCH_OPTIONS_VERSION
          Value: custom001
        - Name: LAUNCH_OPTIONS_REGION
          Value: us-east-1
    Outputs:
      Artifacts:
        DeploymentAssets:
          Files:
          - 'deployment/global-s3-assets/**/*'
          - 'deployment/regional-s3-assets/**/*'
      AutoDiscoverReports:
        Enabled: false
        ReportNamePrefix: rpt
    Configuration:
      Steps:
        - Run: |
            set -e
            cd ./deployment
            chmod +x ./build-s3-dist.sh
            pwd
            ./build-s3-dist.sh $LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET $LAUNCH_OPTIONS_SOLUTION_NAME $LAUNCH_OPTIONS_VERSION
            cd ..
      Container:
        Registry: CODECATALYST
        Image: CodeCatalystLinux_x86_64:2024_03
  upload-to-s3:
    DependsOn:
      - build
    Identifier: aws/build@v1
    Environment:
      Name: hub-account
      Connections:
        - Name: 435185141757
          Role: CodeCatalystWorkflowDevelopmentRole-tbelmega
    Inputs:
      Artifacts:
        - GlobalAssets
        - RegionalAssets
      Sources:
        - WorkflowSource
      Variables:
        - Name: LAUNCH_OPTIONS_SOLUTION_NAME
          Value: AccountAssessment
        - Name: LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET
          Value: solutions-features-aaao-tbelmega
        - Name: LAUNCH_OPTIONS_VERSION
          Value: custom001
        - Name: LAUNCH_OPTIONS_REGION
          Value: us-east-1
    Outputs:
      AutoDiscoverReports:
        Enabled: false
        ReportNamePrefix: rpt
    Configuration:
      Steps:
        - Run: |
            echo $(aws sts get-caller-identity)
            ASSET_BUCKET_NAME=$LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET-$LAUNCH_OPTIONS_REGION
            echo $ASSET_BUCKET_NAME
            aws s3 mb s3://$ASSET_BUCKET_NAME/
            BUCKET_NAME=$LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET-$LAUNCH_OPTIONS_REGION
            aws s3 ls s3://$BUCKET_NAME # test bucket exists - should not give an error
            cd $CATALYST_SOURCE_DIR_DeploymentAssets/deployment
            aws s3 cp global-s3-assets/**/* s3://$BUCKET_NAME/$LAUNCH_OPTIONS_SOLUTION_NAME/$LAUNCH_OPTIONS_VERSION/ --recursive --acl bucket-owner-full-control
            aws s3 cp regional-s3-assets/**/* s3://$BUCKET_NAME/$LAUNCH_OPTIONS_SOLUTION_NAME/$LAUNCH_OPTIONS_VERSION/ --recursive --acl bucket-owner-full-control
            cd ..
      Container:
        Registry: CODECATALYST
        Image: CodeCatalystLinux_x86_64:2024_03
  deploy-hub:
    DependsOn:
      - upload-to-s3 # deploy-hub requires /webui contents in the S3 bucket
    Identifier: aws/build@v1
    Environment:
      Name: hub-account
      Connections:
        - Name: 435185141757
          Role: CodeCatalystWorkflowDevelopmentRole-tbelmega
    Inputs:
      Artifacts:
        - GlobalAssets
        - RegionalAssets
      Sources:
        - WorkflowSource
      Variables:
        - Name: LAUNCH_OPTIONS_SOLUTION_NAME
          Value: AccountAssessment
        - Name: LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET
          Value: solutions-features-aaao-tbelmega
        - Name: LAUNCH_OPTIONS_VERSION
          Value: custom001
        - Name: LAUNCH_OPTIONS_REGION
          Value: us-east-1
        - Name: LAUNCH_OPTIONS_NAMESPACE
          Value: 'aaao-codecat'
        - Name: LAUNCH_OPTIONS_PREFIX
          Value: 'aaao-codecat'
        - Name: LAUNCH_OPTIONS_EMAIL
          Value: 'tbelmega@amazon.com'
        - Name: LAUNCH_OPTIONS_IP_RANGES
          Value: '0.0.0.0/1,128.0.0.0/1'
    Outputs:
      AutoDiscoverReports:
        Enabled: false
        ReportNamePrefix: rpt
    Configuration:
      Steps:
        - Run: |
            cd ./source
            export SOLUTION_VERSION=$LAUNCH_OPTIONS_VERSION
            export SOLUTION_NAME=$LAUNCH_OPTIONS_SOLUTION_NAME
            export DIST_OUTPUT_BUCKET=$LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET
            npm ci
            npm run bootstrap
            npm run deploy -- --parameters DeploymentNamespace=$LAUNCH_OPTIONS_NAMESPACE --parameters CognitoDomainPrefix=$LAUNCH_OPTIONS_PREFIX --parameters UserEmail=$LAUNCH_OPTIONS_EMAIL  --parameters AllowListedIPRanges=$LAUNCH_OPTIONS_IP_RANGES
      Container:
        Registry: CODECATALYST
        Image: CodeCatalystLinux_x86_64:2024_03
  deploy-orgmgmt:
    DependsOn:
      - upload-to-s3 # deploy-spoke requires the template to be in the S3 bucket
    Identifier: aws/build@v1
    Environment:
      Name: orgmgmt-account
      Connections:
        - Name: OrgMgmt
          Role: CodeCatalystWorkflowDevelopmentRole-tbelmega
    Inputs:
      Artifacts:
        - GlobalAssets
        - RegionalAssets
      Sources:
        - WorkflowSource
      Variables:
        - Name: LAUNCH_OPTIONS_SOLUTION_NAME
          Value: AccountAssessment
        - Name: LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET
          Value: solutions-features-aaao-tbelmega
        - Name: LAUNCH_OPTIONS_VERSION
          Value: custom001
        - Name: LAUNCH_OPTIONS_REGION
          Value: us-east-1
        - Name: LAUNCH_OPTIONS_NAMESPACE
          Value: 'aaao-codecat'
        - Name: LAUNCH_OPTIONS_HUB_ACC_ID
          Value: '435185141757'
    Outputs:
      AutoDiscoverReports:
        Enabled: false
        ReportNamePrefix: rpt
    Configuration:
      Steps:
        - Run: |
            cd ./source
            export SOLUTION_VERSION=$LAUNCH_OPTIONS_VERSION
            export SOLUTION_NAME=$LAUNCH_OPTIONS_SOLUTION_NAME
            export DIST_OUTPUT_BUCKET=$LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET
            npm ci
            npm run bootstrap
            npm run deployOrgMgmt -- --parameters DeploymentNamespace=$LAUNCH_OPTIONS_NAMESPACE --parameters HubAccountId=$LAUNCH_OPTIONS_HUB_ACC_ID
      Container:
        Registry: CODECATALYST
        Image: CodeCatalystLinux_x86_64:2024_03
  deploy-spoke1:
    DependsOn:
      - upload-to-s3 # deploy-spoke requires the template to be in the S3 bucket
    Identifier: aws/build@v1
    Environment:
      Name: orgmgmt-account
      Connections:
        - Name: OrgMgmt
          Role: CodeCatalystWorkflowDevelopmentRole-tbelmega
    Inputs:
      Artifacts:
        - GlobalAssets
        - RegionalAssets
      Sources:
        - WorkflowSource
      Variables:
        - Name: LAUNCH_OPTIONS_NAMESPACE
          Value: 'aaao-codecat'
        - Name: LAUNCH_OPTIONS_HUB_ACC_ID
          Value: '435185141757'
    Outputs:
      AutoDiscoverReports:
        Enabled: false
        ReportNamePrefix: rpt
    Configuration:
      Steps:
        - Run: |
            cd ./source
            export SOLUTION_VERSION=$LAUNCH_OPTIONS_VERSION
            export SOLUTION_NAME=$LAUNCH_OPTIONS_SOLUTION_NAME
            export DIST_OUTPUT_BUCKET=$LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET
            aws cloudformation deploy \
            --template-url https://$DIST_OUTPUT_BUCKET.s3.us-west-2.amazonaws.com/$SOLUTION_NAME/$SOLUTION_VERSION/account-assessment-for-aws-organizations-spoke.template \
            --stack-name AccountAssessmentSpoke \
            --region us-east-1 \
            --parameter-overrides \
            DeploymentNamespace=$LAUNCH_OPTIONS_NAMESPACE \
            HubAccountId=$LAUNCH_OPTIONS_HUB_ACC_ID \
      Container:
        Registry: CODECATALYST
        Image: CodeCatalystLinux_x86_64:2024_03
  deploy-spoke2:
    DependsOn:
      - upload-to-s3 # deploy-spoke requires the template to be in the S3 bucket
    Identifier: aws/build@v1
    Environment:
      Name: hub-account
      Connections:
        - Name: 435185141757
          Role: CodeCatalystWorkflowDevelopmentRole-tbelmega
    Inputs:
      Artifacts:
        - GlobalAssets
        - RegionalAssets
      Sources:
        - WorkflowSource
      Variables:
        - Name: LAUNCH_OPTIONS_NAMESPACE
          Value: 'aaao-codecat'
        - Name: LAUNCH_OPTIONS_HUB_ACC_ID
          Value: '435185141757'
    Outputs:
      AutoDiscoverReports:
        Enabled: false
        ReportNamePrefix: rpt
    Configuration:
      Steps:
        - Run: |
            cd ./source
            export SOLUTION_VERSION=$LAUNCH_OPTIONS_VERSION
            export SOLUTION_NAME=$LAUNCH_OPTIONS_SOLUTION_NAME
            export DIST_OUTPUT_BUCKET=$LAUNCH_OPTIONS_DIST_OUTPUT_BUCKET
            npm ci
            npm run bootstrap
            npm run deploySpoke -- --parameters DeploymentNamespace=$LAUNCH_OPTIONS_NAMESPACE --parameters HubAccountId=$LAUNCH_OPTIONS_HUB_ACC_ID
      Container:
        Registry: CODECATALYST
        Image: CodeCatalystLinux_x86_64:2024_03
